name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@780022b48dfc0c2c6b94cfee6a9284850107d037
        with:
          version: 1.3
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main(;subdirs=["", "docs"])'
